// frontend/src/views/Product/WishList.vue
<template>
    <div class="container">
      <div class="row">
        <div class="col-12 text-center">
          <h4 class="pt-3">Your WishList</h4>
        </div>
      </div>
  
      <!-- diaplay products -->
  
      <div class="row">
        <div
          v-for="product of products"
          :key="product.id"
          class="col-md-6 col-xl-4 col-12 pt-3 justify-content-around d-flex"
        >
          <ProductBox :product="product"> </ProductBox>
        </div>
      </div>
    </div>
  </template>
  <script>
  import axios from "axios";
  import ProductBox from "../../components/ProductBox.vue";
  export default {
    components: { ProductBox },
    data() {
      return {
        token: null,
        products: null,
      };
    },
    props: ["baseURL"],
    methods: {
      fetchWishList() {
        axios
          .get(`${this.baseURL}wishlist/${this.token}`)
          .then((data) => {
            this.products = data.data;
          })
          .catch((err) => {
            console.log("err", err);
          });
      },
    },
    mounted() {
      this.token = localStorage.getItem("token");
      this.fetchWishList();
    },
  };
  </script>

// frontend/src/views/Product/WishList.jsx
import React, { useState, useEffect } from 'react';
import axios from 'axios';

const WishList = ({ baseURL }) => {
  const [token, setToken] = useState('');
  const [products, setProducts] = useState([]);

  useEffect(() => {
    const fetchWishList = async () => {
      try {
        const userToken = localStorage.getItem('token');
        setToken(userToken);
        const response = await axios.get(`${baseURL}wishlist/${userToken}`);
        setProducts(response.data);
      } catch (error) {
        console.error('Error fetching wishlist: ', error);
      }
    };

    fetchWishList();
  }, [baseURL]);

  return (
    <div className="container">
      <div className="row">
        <div className="col-12 text-center">
          <h4 className="pt-3">Your WishList</h4>
        </div>
      </div>

      <div className="row">
        {products.map(product => (
          <div key={product.id} className="col-md-6 col-xl-4 col-12 pt-3 justify-content-around d-flex">
            {/* Display Product Details */}
            <div>
              <h5>{product.name}</h5>
              <p>Description: {product.description}</p>
              <p>Price: ${product.price}</p>
              {/* Add more details here as needed */}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default WishList;
