// frontend/src/views/Admin.jsx
import React from 'react';
import { Link } from 'react-router-dom';

const AdminPanel = () => {
  return (
    <div className="container py-4">
      <Link to="/admin/category">
        <button className="btn btn-primary btn-lg">Admin Category</button>
      </Link>
      <br />
      <Link to="/admin/product">
        <button className="btn btn-primary btn-lg">Admin Product</button>
      </Link>
    </div>
  );
};

export default AdminPanel;

// src/views/Admin.vue
<template>
    <div class="container py-4">
        <router-link :to="{name: 'Category'}" >
            <button class="btn btn-primary btn-lg"> Admin Category</button>
        </router-link>
        <br />
        <router-link :to="{name: 'AdminProduct'}" >
            <button class="btn btn-primary btn-lg"> Admin Product</button>
        </router-link>
    </div>
</template>
<script>
export default {
    name: "AdminPanel",
}
</script>
<style>
    .btn {
        margin-bottom: 20px;
    }
</style>
