// frontend/src/views/Signin.jsx
import React, { useState } from 'react';
import axios from 'axios';
import swal from 'sweetalert';

const SignInPage = ({ baseURL, fetchData, history }) => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const signin = async (e) => {
    e.preventDefault();
    try {
      const res = await axios.post(`${baseURL}user/signIn`, { email, password });
      localStorage.setItem('token', res.data.token);
      swal({
        text: 'Login successful',
        icon: 'success',
      });
      fetchData();
      history.push('/home');
    } catch (err) {
      console.log('err', err);
    }
  };

  return (
    <div className="container">
      <div className="row">
        <div className="col-12 justify-content-center d-flex flex-row pt-5">
          <div id="signin" className="flext-item border">
            <h2 className="pt-4">Sign-In</h2>
            <form onSubmit={signin} className="form-group pt-4 pl-4 pr-4">
              <div className="form-group">
                <label>Email </label>
                <input value={email} onChange={(e) => setEmail(e.target.value)} type="email" className="form-control" />
              </div>
              <div className="form-group">
                <label>Password </label>
                <input value={password} onChange={(e) => setPassword(e.target.value)} type="password" className="form-control" />
              </div>
              <button type="submit" className="btn btn-primary mt-2 py-0">Continue</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SignInPage;

// src/views/Signin.vue
<template>
    <div class="conatiner">
      <div class="row">
        <div class="col-12 justify-content-center d-flex flex-row pt-5">
          <div id="signin" class="flext-item border">
            <h2 class="pt-4">Sign-In</h2>
            <form @submit="signin" class="form-group pt-4 pl-4 pr-4">
              <div class="form-group">
                <label>Email </label>
                <input v-model="email" type="email" class="form-control" />
              </div>
              <div class="form-group">
                <label>Password </label>
                <input v-model="password" type="password" class="form-control" />
              </div>
              <button class="btn btn-primary mt-2 py-0">Continue</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </template>
  <script>
  import axios from "axios";
  import swal from "sweetalert";
  export default {
    name: "SignInPage", 
    props: ["baseURL"],
    data() {
      return {
        email: null,
        password: null,
      };
    },
    methods: {
      async signin(e) {
        e.preventDefault();
        const body = {
          email: this.email,
          password: this.password,
        };
        await axios
          .post(`${this.baseURL}user/signIn`, body)
          .then((res) => {
            localStorage.setItem("token", res.data.token);
            swal({
              text: "Login successful",
              icon: "success",
            });
            this.$emit("fetchData");
            this.$router.push({ name: "Home" });
          })
          .catch((err) => console.log("err", err));
      },
    },
  };
  </script>
  <style scoped>
  .btn-primary {
    background-color: #f0c14b;
    color: black;
  }
  
  @media screen and (min-width: 992px) {
    #signin {
      width: 40%;
    }
  }
  </style>
