// src/views/Category/AddCategory.vue
<template>
    <div class="container">
      <div class="row">
        <div class="col-12 text-center">
          <h3 class="pt-3">Add Category</h3>
        </div>
      </div>
      <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
          <form>
            <div class="form-group">
              <label>Name</label>
              <input type="text" class="form-control" v-model="categoryName" />
            </div>
            <div class="form-group">
              <label>Description</label>
              <textarea type="text" class="form-control" v-model="description" />
            </div>
            <div class="form-group">
              <label>Image</label>
              <input type="text" class="form-control" v-model="imageUrl" />
            </div>
            <button type="button" class="btn btn-primary" @click="addCategory">
              Submit
            </button>
          </form>
        </div>
        <div class="col-3"></div>
      </div>
    </div>
  </template>
  <script>
  const axios = require("axios");
  const sweetalert = require("sweetalert");
  export default {
    data() {
      return {
        categoryName: "",
        description: "",
        imageUrl: "",
      };
    },
    methods: {
      addCategory() {
        console.log(this.categoryName, this.description);
        const newCategory = {
          categoryName: this.categoryName,
          description: this.description,
          imageUrl: this.imageUrl,
        };
  
        const baseURL = "https://limitless-lake-55070.herokuapp.com";
  
        axios({
          method: "post",
          url: `${baseURL}/category/create`,
          data: JSON.stringify(newCategory),
          headers: {
            "Content-Type": "application/json",
          },
        })
          .then(() => {
            sweetalert({
              text: "Category added successfully",
              icon: "success",
            });
          })
          .catch((err) => {
            console.log(err);
          });
      },
    },
  };
  </script>
  <style scoped></style>

// frontend/src/views/Category/AddCategory.jsx
import React, { useState } from 'react';
import axios from 'axios';
import swal from 'sweetalert';

const AddCategory = () => {
  const [categoryName, setCategoryName] = useState('');
  const [description, setDescription] = useState('');
  const [imageUrl, setImageUrl] = useState('');

  const addCategory = () => {
    const newCategory = {
      categoryName,
      description,
      imageUrl,
    };

    const baseURL = 'https://limitless-lake-55070.herokuapp.com';

    axios({
      method: 'post',
      url: `${baseURL}/category/create`,
      data: JSON.stringify(newCategory),
      headers: {
        'Content-Type': 'application/json',
      },
    })
      .then(() => {
        swal({
          text: 'Category added successfully',
          icon: 'success',
        });
      })
      .catch((err) => {
        console.log(err);
      });
  };

  return (
    <div className="container">
      <div className="row">
        <div className="col-12 text-center">
          <h3 className="pt-3">Add Category</h3>
        </div>
      </div>
      <div className="row">
        <div className="col-3"></div>
        <div className="col-6">
          <form>
            <div className="form-group">
              <label>Name</label>
              <input
                type="text"
                className="form-control"
                value={categoryName}
                onChange={(e) => setCategoryName(e.target.value)}
              />
            </div>
            <div className="form-group">
              <label>Description</label>
              <textarea
                type="text"
                className="form-control"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
              />
            </div>
            <div className="form-group">
              <label>Image</label>
              <input
                type="text"
                className="form-control"
                value={imageUrl}
                onChange={(e) => setImageUrl(e.target.value)}
              />
            </div>
            <button type="button" className="btn btn-primary" onClick={addCategory}>
              Submit
            </button>
          </form>
        </div>
        <div className="col-3"></div>
      </div>
    </div>
  );
};

export default AddCategory;
