// frontend/src/views/Category/Category.vue
<template>
    <div class="container">
      <div class="row">
        <div class="col-12 text-center">
          <h3 class="pt-3">Our Categories</h3>
          <router-link :to="{ name: 'AddCategory' }">
            <button class="btn" style="float:right">Add Category</button>
          </router-link>
        </div>
      </div>
      <div class="row">
        <div
          v-for="category of categories"
          :key="category.id"
          class="col-xl-4 col-md-6 col-12 pt-3 d-flex"
        >
          <CategoryBox :category="category"> </CategoryBox>
        </div>
      </div>
    </div>
  </template>
  <script>
  import CategoryBox from "../../components/Category/CategoryBox.vue";
  export default {
    name: "CategoryView",
    props:["categories"],
    components: { CategoryBox },
    data() {
      return {
        baseURL: "https://limitless-lake-55070.herokuapp.com",
      };
    },
    methods: {
    },
    mounted() {},
  };
  </script>
  <style scoped></style>

// frontend/src/views/Category/Category.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import CategoryBox from '../../components/Category/CategoryBox';

const CategoryView = ({ categories }) => {
  return (
    <div className="container">
      <div className="row">
        <div className="col-12 text-center">
          <h3 className="pt-3">Our Categories</h3>
          <Link to="/AddCategory">
            <button className="btn" style={{ float: 'right' }}>
              Add Category
            </button>
          </Link>
        </div>
      </div>
      <div className="row">
        {categories.map((category) => (
          <div key={category.id} className="col-xl-4 col-md-6 col-12 pt-3 d-flex">
            <CategoryBox category={category} />
          </div>
        ))}
      </div>
    </div>
  );
};

export default CategoryView;
