// frontend/src/components/Navbar.jsx
import React from 'react';
import { Link } from 'react-router-dom';

const AppNavbar = ({ cartCount, resetCartCount }) => {
  const token = localStorage.getItem('token');

  const signout = () => {
    localStorage.removeItem('token');
    resetCartCount();
    alert('Logged you out. Visit again');
    // Assuming this.props.history.push is available when using React Router for navigation
    this.props.history.push('/Home');
  };

  return (
    <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
      <Link className="navbar-brand" to="/Home">
        <img id="logo" src="../assets/icon.png" alt="Logo" />
      </Link>
      <button
        className="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span className="navbar-toggler-icon"></span>
      </button>
      <div className="collapse navbar-collapse" id="navbarSupportedContent">
        <form className="form-inline ml-auto mr-auto">
          <div className="input-group">
            <input
              size="100"
              type="text"
              className="form-control"
              placeholder="Search Items"
              aria-label="Username"
              aria-describedby="basic-addon1"
            />
            <div className="input-group-prepend">
              <span className="input-group-text" id="search-button-navbar">
                {/* SVG icon */}
              </span>
            </div>
          </div>
        </form>
        <ul className="navbar-nav ml-auto">
          {/* Dropdown for browse */}
          {/* Dropdown for account */}
          <li className="nav-item">
            <div id="cart" style={{ position: 'relative' }}>
              <span id="nav-cart-count">{cartCount}</span>
              <Link className="text-light" to="/Cart">
                <i className="fa fa-shopping-cart" style={{ fontSize: '36px' }}></i>
              </Link>
            </div>
          </li>
        </ul>
      </div>
    </nav>
  );
};

export default AppNavbar;

// src/components/Navbar.vue

<template>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <!-- Navbar content -->
      <!--    Logo-->
      <router-link class="navbar-brand" :to="{ name: 'Home' }">
        <img id="logo" src="../assets/icon.png" />
      </router-link>
      <!--    Burger Button-->
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!--      Search Bar-->
        <form class="form-inline ml-auto mr-auto">
          <div class="input-group">
            <input
              size="100"
              type="text"
              class="form-control"
              placeholder="Search Items"
              aria-label="Username"
              aria-describedby="basic-addon1"
            />
            <div class="input-group-prepend">
              <span class="input-group-text" id="search-button-navbar">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="16"
                  height="16"
                  fill="currentColor"
                  class="bi bi-search"
                  viewBox="0 0 16 16"
                >
                  <path
                    d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"
                  />
                </svg>
              </span>
            </div>
          </div>
        </form>
        <!-- dropdown for browse -->
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a
              class="nav-link text-light dropdown-toggle"
              href="#"
              id="navbarAccount"
              data-toggle="dropdown"
            >
              Browse
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarAccount">
              <router-link class="dropdown-item" :to="{ name: 'Home' }"
                >Home
              </router-link>
              <router-link class="dropdown-item" :to="{ name: 'Home' }"
                >Product
              </router-link>
              <router-link class="dropdown-item" :to="{ name: 'Home' }"
                >Category
              </router-link>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle text-light"
              href="#"
              id="navbarAccount"
              data-toggle="dropdown"
            >
              Accounts
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarAccount">
              <router-link
                v-if="token"
                class="dropdown-item"
                :to="{ name: 'WishList' }"
                >Wishlist
              </router-link>
              <router-link
                v-if="!token"
                class="dropdown-item"
                :to="{ name: 'Signup' }"
                >Sign up
              </router-link>
              <router-link
                v-if="!token"
                class="dropdown-item"
                :to="{ name: 'Signin' }"
                >Sign in
              </router-link>
              <a class="dropdown-item" v-if="token" href="#" @click="signout"
                >Sign out
              </a>
            </div>
          </li>
          <li class="nav-item">
            <div id="cart" style="position:relative">
              <span id="nav-cart-count">{{ cartCount }}</span>
              <router-link class="text-light" :to="{ name: 'Cart' }">
                <i class="fa fa-shopping-cart" style="font-size:36px"></i>
              </router-link>
            </div>
          </li>
        </ul>
        <!-- dropdown for account -->
      </div>
    </nav>
  </template>
  <script>
  import swal from "sweetalert";
  export default {
    name: "AppNavbar",
    props: ["cartCount"],
    data() {
      return {
        token: null,
      };
    },
    methods: {
      signout() {
        localStorage.removeItem("token");
        this.token = null;
        swal({
          text: "Logged you out. Visit again",
          icon: "success",
        });
        this.$emit("resetCartCount");
        this.$router.push({ name: "Home" });
      },
    },
    mounted() {
      this.token = localStorage.getItem("token");
    },
  };
  </script>
  <style scoped>
  #logo {
    width: 150px;
    margin-left: 20px;
    margin-right: 20px;
  }
  .nav-link {
    color: rgba(255, 255, 255);
  }
  
  #search-button-navbar {
    background-color: #febd69;
    border-color: #febd69;
    border-top-right-radius: 2px;
    border-bottom-right-radius: 2px;
  }
  
  #nav-cart-count {
    background-color: red;
    color: white;
    border-radius: 50%;
    height: 15px;
    width: 15px;
    font-size: 15px;
    align-items: center;
  
    display: flex;
    justify-content: center;
  
    position: absolute;
    margin-left: 10px;
  }
  </style>
